Repository Matic-Digital/NX-2025, pull requests merged in 2025-09, with the labels that each got.

#56 fixed mobile service cards and gap
  src/components/ContentGrid.tsx
  src/components/PageLayout/PageLayout.tsx
  src/components/ServiceCarousel.tsx
  src/components/global/PageCard.tsx
  src/components/global/ServiceCard.tsx
  src/components/global/Testimonials.tsx
  src/components/media/AirImage.tsx
  src/types/contentful/Collection.ts
  src/types/contentful/TeamMember.ts
Labels: bug, enhancement

#59 add keyboard navigation and mobile-responsive layout for sliders
  src/components/ContactCard/ContactCard.tsx
  src/components/SectionHeading/SectionHeading.tsx
  src/components/Slider.tsx
  src/components/global/ModalCtaButton.tsx
  src/components/global/ServiceCard.tsx
  src/components/media/AirImage.tsx
Labels: bug, enhancement

#65 removed solution card hover state on mobile
  src/components/SolutionCard.tsx
Labels: bug

#66 fixed ticket ID-766
  src/components/OfficeLocation.tsx
Labels: bug

#69 Feat/mega menu
  package-lock.json
  package.json
  src/components/Header/Header.tsx
  src/components/Header/HeaderSchema.ts
  src/components/MegaMenu/MegaMenu.tsx
  src/components/MegaMenu/MegaMenuApi.ts
  src/components/MegaMenu/MegaMenuSchema.ts
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuApi.ts
  src/components/Menu/MenuSchema.ts
  src/components/MenuItem/MenuItem.tsx
  src/components/MenuItem/MenuItemApi.ts
  src/components/MenuItem/MenuItemSchema.ts
  src/components/ui/collapsible.tsx
  src/contexts/MegaMenuContext.tsx
  src/lib/contentful-api/graphql-fields.ts
Labels: enhancement
